version: "3"
volumes:
  gotify-data:
services:
  caddy:
    build:
      context: caddy
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
    expose:
      - "$HTTP_PORT"
      - "$HTTPS_PORT"
    restart: always
    depends_on:
      - gotify
  gotify:
    image: ghcr.io/gotify/server
    volumes:
      - gotify-data:/app/data
    expose:
      - "80"
    environment:
      TZ: "$TZ"
      GOTIFY_DEFAULTUSER_NAME: "$GOTIFY_DEFAULTUSER_NAME"
      GOTIFY_DEFAULTUSER_PASS: "$GOTIFY_DEFAULTUSER_PASS"
    restart: always
